// Bundles the engine and the app into one page. `index.html` is the standalone site,
// `dist/outpost.html` is the same page without the outer document, for embedding.
import { build } from 'esbuild';
import fs from 'node:fs';

const css = fs.readFileSync('app/style.css', 'utf8');
const markup = fs.readFileSync('app/markup.html', 'utf8');
fs.writeFileSync('app/_assets.js', `// Generated by build.mjs from style.css and markup.html.\nexport const CSS = ${JSON.stringify(css)};\nexport const MARKUP = ${JSON.stringify(markup)};\n`);
const common = { bundle: true, format: 'iife', minify: true, write: false, target: 'es2019', legalComments: 'none' };
const r = await build({ ...common, entryPoints: ['app/standalone.js'] });
const js = r.outputFiles[0].text;
// The embed build is wrapped in a function, so it only runs once the host page has loaded three.js.
const e = await build({ ...common, entryPoints: ['app/embed.js'], globalName: '__OP' });
const embedJs = `window.__opMount=function(host,opts){${e.outputFiles[0].text}\nreturn __OP.mount(host,opts);};\n`;
const fonts = 'https://fonts.googleapis.com/css2?family=Bricolage+Grotesque:opsz,wght@12..96,400..800&family=JetBrains+Mono:wght@400..700&display=swap';
const libs = [
  'https://cdnjs.cloudflare.com/ajax/libs/three.js/r128/three.min.js',
  'https://cdn.jsdelivr.net/npm/three@0.128.0/examples/js/controls/OrbitControls.js',
].map(u => `<script src="${u}"></script>`).join('\n');

const page = `<title>Outpost</title>
<link rel="stylesheet" href="${fonts}">
<style>
${css}</style>
${markup}
${libs}
<script>
${js}</script>
`;
fs.mkdirSync('dist', { recursive: true });
fs.writeFileSync('dist/outpost.html', page);
fs.writeFileSync('dist/outpost-embed.js', embedJs);
fs.writeFileSync('index.html', `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">
<meta name="robots" content="noindex, nofollow, noarchive">
<meta name="description" content="Outpost is a base of operations for AI agents: see your crew at work, set what each bot may touch, and decide the risky calls yourself.">
<meta name="theme-color" content="#0B0C26">
<link rel="icon" href="brand/favicon.svg">
</head>
<body>
${page}</body>
</html>
`);
console.log('built', (page.length / 1024).toFixed(0) + ' KB, embed', (embedJs.length / 1024).toFixed(0) + ' KB');
