// Bundles the engine and the app into one page. `index.html` is the standalone site,
// `dist/outpost.html` is the same page without the outer document, for embedding.
import { build } from 'esbuild';
import fs from 'node:fs';

const css = fs.readFileSync('app/style.css', 'utf8');
const markup = fs.readFileSync('app/markup.html', 'utf8');
fs.writeFileSync('app/_assets.js', `// Generated by build.mjs from style.css and markup.html.\nexport const CSS = ${JSON.stringify(css)};\nexport const MARKUP = ${JSON.stringify(markup)};\n`);
const common = { bundle: true, format: 'iife', minify: true, write: false, target: 'es2019', legalComments: 'none' };
const r = await build({ ...common, entryPoints: ['app/standalone.js'] });
const js = r.outputFiles[0].text;
// The embed build is wrapped in a function, so it only runs once the host page has loaded three.js.
const e = await build({ ...common, entryPoints: ['app/embed.js'], globalName: '__OP' });
const embedJs = `window.__opMount=function(host,opts){${e.outputFiles[0].text}\nreturn __OP.mount(host,opts);};\n`;
const fonts = 'https://fonts.googleapis.com/css2?family=Unbounded:wght@400..700&family=Geist:wght@400..700&family=JetBrains+Mono:wght@400..700&display=swap';
const libs = [
  'https://cdnjs.cloudflare.com/ajax/libs/three.js/r128/three.min.js',
  'https://cdn.jsdelivr.net/npm/three@0.128.0/examples/js/controls/OrbitControls.js',
].map(u => `<script src="${u}"></script>`).join('\n');

const page = `<title>Outpost</title>
<link rel="stylesheet" href="${fonts}">
<style>
${css}</style>
${markup}
${libs}
<script>
${js}</script>
`;
fs.mkdirSync('dist', { recursive: true });
fs.writeFileSync('dist/outpost.html', page);
fs.writeFileSync('dist/outpost-embed.js', embedJs);
fs.writeFileSync('index.html', `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">
<meta name="robots" content="noindex, nofollow, noarchive">
<meta name="description" content="Outpost is the control room for the person who runs a company's AI agents. Each bot acts alone up to a limit it has earned, and anything risky waits at the Gate for a person's yes. Interactive demo, sample data.">
<meta property="og:title" content="Outpost">
<meta property="og:description" content="Outpost is the control room for the person who runs a company&#x27;s AI agents. Each bot acts alone up to a limit it has earned, and anything risky waits at the Gate for a person&#x27;s yes. Interactive demo, sample data.">
<meta property="og:type" content="website">
<meta property="og:url" content="https://murtuzabuilds.github.io/outpost/">
<meta property="og:image" content="https://murtuzabuilds.github.io/outpost/docs/og.png">
<meta property="og:image:width" content="1200">
<meta property="og:image:height" content="630">
<meta name="twitter:card" content="summary_large_image">
<meta name="theme-color" content="#04050B">
<link rel="icon" href="brand/favicon.svg">
</head>
<body>
${page}</body>
</html>
`);
console.log('built', (page.length / 1024).toFixed(0) + ' KB, embed', (embedJs.length / 1024).toFixed(0) + ' KB');
